DoctorsOffice/Models/Doctor.cs
using System.Collections.Generic;

namespace DoctorsOffice.Models
{
  public class Doctor
  {
    public Doctor()
    {
      this.JoinDoctorPatient = new HashSet<DoctorPatient>();
      this.JoinDoctorSpecialty = new HashSet<DoctorSpecialty>();
    }

    public int DoctorId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<DoctorPatient> JoinDoctorPatient { get; set; }
    public virtual ICollection<DoctorSpecialty> JoinDoctorSpecialty { get; set; }
  }
}

DoctorsOffice/Controllers/DoctorsController.cs
using DoctorsOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DoctorsOffice.Controllers
{
  public class DoctorsController: Controller
  {
    private readonly DoctorsOfficeContext _db;

    public DoctorsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Doctors.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.PatientId = new SelectList(_db.Patients, "PatientId", "Name");
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor, int PatientId, int SpecialtyId)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      if (PatientId != 0)
      {
        _db.DoctorPatients.Add(new DoctorPatient() {PatientId = PatientId, DoctorId = doctor.DoctorId});
        _db.SaveChanges();
      }
      if (SpecialtyId != 0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() {SpecialtyId = SpecialtyId, DoctorId = doctor.DoctorId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Doctor foundDoctor = _db.Doctors
        .Include(doctor => doctor.JoinDoctorPatient)
        .ThenInclude(joinPatient => joinPatient.Patient)
        .Include(doctor => doctor.JoinDoctorSpecialty)
        .ThenInclude(joinSpecialty => joinSpecialty.Specialty)
        .FirstOrDefault(model => model.DoctorId == id);
      return View(foundDoctor);
    }

    public ActionResult Edit(int id)
    {
      Doctor foundDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(foundDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var foundDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(foundDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var foundDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(foundDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeletePatient(int joinId)
    {
      var joinEntry = _db.DoctorPatients.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      int savedDoctor = joinEntry.DoctorId;
      _db.DoctorPatients.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = savedDoctor});
    }

    [HttpPost]
    public ActionResult DeleteSpecialty(int joinId)
    {
      var joinEntry = _db.DoctorSpecialty.FirstOrDefault(entry => entry.DoctorSpecialtyId == joinId);
      int savedDoctor = joinEntry.DoctorId;
      _db.DoctorSpecialty.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = savedDoctor});
    }

    public ActionResult AddPatient(int id)
    {
      Doctor foundDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      ViewBag.PatientId = new SelectList(_db.Patients, "PatientId", "Name");
      return View(foundDoctor);
    }

    [HttpPost]
    public ActionResult AddPatient(Doctor doctor, int PatientId)
    {
      if (PatientId !=0)
      {
        _db.DoctorPatients.Add(new DoctorPatient() {PatientId = PatientId, DoctorId = doctor.DoctorId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
  }
}

DoctorsOffice/Views/Doctors/AddPatient.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h2>Add a patient</h2>

<hr>

<h4>Add a Patient to this Doctor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.Label("Select Patient")
  @Html.DropDownList("PatientId")

  <input type="submit" value="add" />
}

DoctorsOffice/Views/Doctors/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h2>Enter new doctor</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Select Specialty")
  @Html.DropDownList("SpecialtyId")

  @Html.Label("Select Patient")
  @Html.DropDownList("PatientId")

  <input type="submit" value="Save" />
}

DoctorsOffice/Views/Doctors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h2>Delete</h2>

<h4>Delete this doctor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger" />
}

DoctorsOffice/Views/Doctors/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor

<h2>Doctor Details</h2>

<h4>Doctor:</h4>
<p><strong>@Html.DisplayNameFor(model => model.Name): </strong>@Html.DisplayFor(model => model.Name)</p>

@if (Model.JoinDoctorPatient.Count == 0)
{
  <p>This doctor hasn't been assigned any patients.</p>
}
else
{
  <p><strong>Patients:</strong></p>
  <ul>
    @foreach (var join in Model.JoinDoctorPatient)
    {
      <li>@join.Patient.Name</li>
      @using (Html.BeginForm("DeletePatient", "Doctors"))
      {
        <!-- Modal Button Trigger -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Patient">
          Delete Patient
        </button>

        <!-- Modal -->
        <div class="modal fade" id="Patient" tabindex="-1" aria-labelledby="PatientLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="PatientLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Clicking delete will make this action final.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                @using (Html.BeginForm("DeletePatient", "Doctors"))
                {
                  @Html.Hidden("joinId", @join.DoctorPatientId)
                  <input type="submit" value="Delete"  class="btn btn-danger"/>
                }
              </div>
            </div>
          </div>
        </div>
      }
    }
  </ul>
}

@if (Model.JoinDoctorSpecialty.Count == 0)
{
  <p>This doctor hasn't been assigned any specialties.</p>
}
else
{
  <p><strong>Specialties:</strong></p>
  <ul>
    @foreach (var join in Model.JoinDoctorSpecialty)
    {
      <li>@join.Specialty.Name</li>
      @using (Html.BeginForm("DeleteSpecialty", "Doctors"))
      {
        <!-- Modal Button Trigger -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#SpecialtyModal">
        Delete Specialty
        </button>

        <!-- Modal -->
        <div class="modal fade" id="SpecialtyModal" tabindex="-1" aria-labelledby="SpecialtyModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="SpecialtyModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Clicking delete will make this action final.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                @using (Html.BeginForm("DeleteSpecialty", "Doctors"))
                {
                  @Html.Hidden("joinId", @join.DoctorSpecialtyId)
                  <input type="submit" value="Delete"  class="btn btn-danger"/>
                }
              </div>
            </div>
          </div>
        </div>
      }
    }
  </ul>
}



<p>@Html.ActionLink("Edit Doctor", "Edit", new { id = Model.DoctorId })</p>
<p>@Html.ActionLink("Delete Doctor", "Delete", new { id = Model.DoctorId})</p>
<p>@Html.ActionLink("Add Patient", "AddPatient", new {id = Model.DoctorId})</p>

DoctorsOffice/Views/Doctors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor 

<h2>Edit</h2>

<h4>Edit this doctor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save"/>
}

DoctorsOffice/Views/Doctors/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Doctor>

<h2>Doctors</h2>

@if (@Model.Count == 0)
{
  <p>There are no doctors in the system.</p>
}

<ul>
  @foreach (Doctor doctor in Model)
  {
    <li>@Html.ActionLink($"{doctor.Name}", "Details", new { id = doctor.DoctorId})</li>
  }
</ul>

<p>@Html.ActionLink("Add doctor", "Create")</p>