DoctorsOffice/Models/Specialty.cs
using System.Collections.Generic;

namespace DoctorsOffice.Models
{
  public class Specialty
  {
    public Specialty()
    {
      this.JoinDoctorSpecialty = new HashSet<DoctorSpecialty>();
    }

    public int SpecialtyId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<DoctorSpecialty> JoinDoctorSpecialty { get; set; }
  }
}

DoctorsOffice/Controllers/SpecialtiesController.cs
using DoctorsOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DoctorsOffice.Controllers
{
  public class SpecialtiesController : Controller
  {
    private readonly DoctorsOfficeContext _db;

    public SpecialtiesController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Specialties.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Specialty specialty, int DoctorId)
    {
      _db.Specialties.Add(specialty);
      _db.SaveChanges();
      if (DoctorId != 0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() {DoctorId = DoctorId, SpecialtyId = specialty.SpecialtyId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Specialty foundSpecialty = _db.Specialties
        .Include(specialty => specialty.JoinDoctorSpecialty)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(model => model.SpecialtyId == id);
      return View(foundSpecialty);
    }

    public ActionResult Edit(int id)
    {
      var foundSpecialty = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(foundSpecialty);
    }

    [HttpPost]
    public ActionResult Edit(Specialty specialty, int DoctorId)
    {
      if (DoctorId !=0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() {DoctorId = DoctorId, SpecialtyId = specialty.SpecialtyId});        
      }
      _db.Entry(specialty).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Specialty foundSpecialty = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
      return View(foundSpecialty);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Specialty foundSpecialty = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
      _db.Specialties.Remove(foundSpecialty);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDoctor(int id)
    {
      Specialty foundSpecialty = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(foundSpecialty);
    }

    [HttpPost]
    public ActionResult AddDoctor(Specialty specialty, int DoctorId)
    {
      if (DoctorId !=0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() {DoctorId = DoctorId, SpecialtyId = specialty.SpecialtyId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteSpecialty(int joinId)
    {
      var joinEntry = _db.DoctorSpecialty.FirstOrDefault(entry => entry.DoctorSpecialtyId == joinId);
      int savedSpecialty = joinEntry.SpecialtyId;
      _db.DoctorSpecialty.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = savedSpecialty});
    }
  }
}

DoctorsOffice/Views/Specialties/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty

<h2>Add a Doctor</h2>

<hr>

<h4>Add a Doctor to this Specialty: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.SpecialtyId)

  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="add" />
}

DoctorsOffice/Views/Specialties/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty

<h2>Enter new specialty</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  
  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Save" />
}

DoctorsOffice/Views/Specialties/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty

<h2>Delete</h2>

<h4>Delete this specialty: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger" />
}

DoctorsOffice/Views/Specialties/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty

<h2>Specialty Details</h2>

<h4>Specialty:</h4>
<p><strong>@Html.DisplayNameFor(model => model.Name): </strong>@Html.DisplayFor(model => model.Name)</p>

@if (Model.JoinDoctorSpecialty.Count == 0)
{
  <p>This specialty hasn't been assigned any doctors.</p>
}
else
{
  <p><strong>Doctors:</strong></p>
  <ul>
    @foreach (var join in Model.JoinDoctorSpecialty)
    {
      <li>@join.Doctor.Name</li>
      <!-- Modal Button Trigger -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Delete Doctor
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Clicking delete will make this action final.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              @using (Html.BeginForm("DeleteDoctor", "Specialties"))
              {
                @Html.Hidden("joinId", @join.DoctorSpecialtyId)
                <input type="submit" value="Delete"  class="btn btn-danger"/>
              }
            </div>
          </div>
        </div>
      </div>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Specialty", "Edit", new { id = Model.SpecialtyId })</p>
<p>@Html.ActionLink("Delete Specialty", "Delete", new { id = Model.SpecialtyId})</p>
<p>@Html.ActionLink("Add Doctor", "AddDoctor", new {id = Model.SpecialtyId})</p>

DoctorsOffice/Views/Specialties/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty

<h2>Edit</h2>

<h4>Edit this specialty: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.SpecialtyId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save"/>
}

DoctorsOffice/Views/Specialties/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Specialty>

<h2>Specialties</h2>

@if (@Model.Count == 0)
{
  <p>There are no specialties in the system.</p>
}

<ul>
  @foreach (Specialty specialty in Model)
  {
    <li>@Html.ActionLink($"{specialty.Name}", "Details", new { id = specialty.SpecialtyId})</li>
  }
</ul>

<p>@Html.ActionLink("Add specialty", "Create")</p>