DoctorsOffice/Models/Patient.cs
using System;
using System.Collections.Generic;
namespace DoctorsOffice.Models
{
  public class Patient
  {
    public Patient()
    {
      this.JoinDoctorPatient = new HashSet<DoctorPatient>();
    }

    public int PatientId { get; set; }
    public string Name { get; set; }
    public DateTime Birthday { get; set; }
    public virtual ICollection<DoctorPatient> JoinDoctorPatient { get; set; }
  }
}

DoctorsOffice/Controllers/PatientsController.cs
using DoctorsOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DoctorsOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DoctorsOfficeContext _db;

    public PatientsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Patients.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      _db.SaveChanges();
      if (DoctorId != 0)
      {
        _db.DoctorPatients.Add(new DoctorPatient() {DoctorId = DoctorId, PatientId = patient.PatientId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Patient foundPatient = _db.Patients
        .Include(patient => patient.JoinDoctorPatient)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(model => model.PatientId == id);
      return View(foundPatient);
    }

    public ActionResult Edit(int id)
    {
      var foundPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(foundPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      if (DoctorId !=0)
      {
        _db.DoctorPatients.Add(new DoctorPatient() {DoctorId = DoctorId, PatientId = patient.PatientId});        
      }
      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Patient foundPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      return View(foundPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Patient foundPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      _db.Patients.Remove(foundPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDoctor(int id)
    {
      Patient foundPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(foundPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if (DoctorId !=0)
      {
        _db.DoctorPatients.Add(new DoctorPatient() {DoctorId = DoctorId, PatientId = patient.PatientId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      var joinEntry = _db.DoctorPatients.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      int savedPatient = joinEntry.PatientId;
      _db.DoctorPatients.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = savedPatient});
    }
  }
}

DoctorsOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Add a Doctor</h2>

<hr>

<h4>Add a Doctor to this Patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="add" />
}

DoctorsOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Enter new patient</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  
  @Html.LabelFor(model => model.Birthday)
  @Html.TextBoxFor(model => model.Birthday, new {type="date"})

  @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId")

  <input type="submit" value="Save" />
}

DoctorsOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Delete</h2>

<h4>Delete this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-danger" />
}

DoctorsOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Patient Details</h2>

<h4>Patient:</h4>
<p><strong>@Html.DisplayNameFor(model => model.Name): </strong>@Html.DisplayFor(model => model.Name)</p>
<p><strong>@Html.DisplayNameFor(model => model.Birthday): </strong>@Html.DisplayFor(model => model.Birthday)</p>

@if (Model.JoinDoctorPatient.Count == 0)
{
  <p>This patient hasn't been assigned any doctors.</p>
}
else
{
  <p><strong>Doctors:</strong></p>
  <ul>
    @foreach (var join in Model.JoinDoctorPatient)
    {
      <li>@join.Doctor.Name</li>
      <!-- Modal Button Trigger -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Delete Doctor
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Clicking delete will make this action final.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              @using (Html.BeginForm("DeleteDoctor", "Patients"))
              {
                @Html.Hidden("joinId", @join.DoctorPatientId)
                <input type="submit" value="Delete"  class="btn btn-danger"/>
              }
            </div>
          </div>
        </div>
      </div>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Patient", "Edit", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Delete Patient", "Delete", new { id = Model.PatientId})</p>
<p>@Html.ActionLink("Add Doctor", "AddDoctor", new {id = Model.PatientId})</p>

DoctorsOffice/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<h2>Edit</h2>

<h4>Edit this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Birthday)
  @Html.EditorFor(model => model.Birthday, new {type="date"})

  <!-- @Html.Label("Select Doctor")
  @Html.DropDownList("DoctorId") -->

  <input type="submit" value="Save"/>
}

DoctorsOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Patient>

<h2>Patients</h2>

@if (@Model.Count == 0)
{
  <p>There are no patients in the system.</p>
}

<ul>
  @foreach (Patient patient in Model)
  {
    <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId})</li>
  }
</ul>

<p>@Html.ActionLink("Add patient", "Create")</p>